/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Oct 24 2023
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }